Demo/RxSwiftExtDemo/RxSwiftExtPlayground.playground/Pages/unwrap.xcplaygroundpage/Contents.swift, Demo/RxSwiftExtDemo/RxSwiftExtPlayground.playground/contents.xcplayground, Demo/RxSwiftExtDemoTests/UnwrapTests.swift, Source/unwrap.swift
as per https://github.com/RxSwiftCommunity/RxSwift-Ext/issues/2
=> unwrap tests, examples, docs

CONDUCT.md
=> Add code of conduct

Demo/RxSwiftExtDemo.xcodeproj/project.pbxproj, Demo/RxSwiftExtDemo/RxSwiftExtPlayground.playground/Pages/not.xcplaygroundpage/Contents.swift, Demo/RxSwiftExtDemo/RxSwiftExtPlayground.playground/Pages/not.xcplaygroundpage/timeline.xctimeline, Demo/RxSwiftExtDemo/RxSwiftExtPlayground.playground/contents.xcplayground, Demo/RxSwiftExtDemoTests/notTests.swift, Source/not.swift
=> not() Operator

Demo/RxSwiftExtDemo.xcodeproj/project.pbxproj, Demo/RxSwiftExtDemoTests/DistinctTests.swift, Source/distinct.swift
=> Added distinct operator and tests to cover its logic

Demo/RxSwiftExtDemo.xcodeproj/project.pbxproj
* make playground work with CP 1.0.0
* add back test target for the demo project
=> [WIP] Mt cp1.0.0

Demo/RxSwiftExtDemo.xcodeproj/project.pbxproj, Demo/RxSwiftExtDemoTests/RetryWithBehaviorTests.swift, Source/retryWithBehavior.swift
Hello.
I have found a conversation #15 about retry/repeat operators. So here is my attempt to implement retry operator. This is my first contribution to open source, so maybe I did something wrong:)
If it's OK, I will update Readme with information about new operator.
=> Retry with delay implementation

Demo/RxSwiftExtDemo/RxSwiftExtPlayground.playground/Pages/cascade.xcplaygroundpage/timeline.xctimeline, Demo/RxSwiftExtDemo/RxSwiftExtPlayground.playground/Pages/distinct.xcplaygroundpage/timeline.xctimeline, Demo/RxSwiftExtDemo/RxSwiftExtPlayground.playground/Pages/retryWithBehavior.xcplaygroundpage/Contents.swift, Demo/RxSwiftExtDemo/RxSwiftExtPlayground.playground/contents.xcplayground, Readme.md, Source/retryWithBehavior.swift
Hello.
I added playground page for retry method. 
And readme.md now contains section with explanation, how it works.
=> Add documentation for retry method

Demo/Podfile
@fpillet - this should fix the failing imports inside the playground (copied the post pod install adjustments from Boris' code)
=> Boris is the best #yatusabes

Demo/RxSwiftExtDemo.xcodeproj/project.pbxproj, Demo/RxSwiftExtDemo/RxSwiftExtPlayground.playground/Pages/Index.xcplaygroundpage/Contents.swift, Demo/RxSwiftExtDemo/RxSwiftExtPlayground.playground/Pages/pausable.xcplaygroundpage/Contents.swift, Demo/RxSwiftExtDemoTests/pausableTests.swift, Readme.md, Source/pausable.swift
=> Add pausable operator

Cartfile, Cartfile.resolved
This allows Travis-CI to run unit tests with RxSwift 3.1.0
=> Update RxSwift version in cartfile

RxSwiftExt.xcodeproj/project.pbxproj, Tests/RxSwift/materialized+elementsTests.swift, materialized+elements.swift
=> Implements errors() & elements() for materialized Observable

.travis.yml, Cartfile.resolved
This should help Travis and Carthage build and test our project
=> Update Travis config and Cartfile.resolved

RxSwiftExt.xcodeproj/project.pbxproj, Source/RxSwift/customOperator.swift, Source/RxSwift/filterMap.swift, Tests/RxSwift/filterMapTests.swift
I had to implement `filterMap` for my own use and I had the idea to make it a bit more generic using a kind of `flatMap` using a `CustomOperator` type.
I'm providing both to the community.
=> CustomOperator and FilterMap

RxSwiftExt.xcodeproj/project.pbxproj, Source/RxSwift/pausableBuffered.swift, Tests/RxSwift/pausableBufferedTests.swift
http://rxmarbles.com/#pausableBuffered
~~Implementation from existing `pausable` operator.~~
Use @mkko implementation https://github.com/RxSwiftCommunity/RxSwiftExt/issues/77
=> PausableBuffered

Source/RxSwift/unwrap.swift
Saw [this post](http://rx-marin.com/post/rxswift-rxcocoa-custom-convenience-operators-part2/) and took a crack at improving unwrap. API/usage is unchanged.
=> Made unwrap more concise

.travis.yml
Hello.
This is small fixes in .travis.yml in order to finally run tests.
=> Fix CI for Swift4.0 branch

RxSwiftExt.podspec
=> Include curry.swift in `Core` subspec

Source/RxSwift/unwrap.swift
Make *unwrap* function concise and easier to follow.
=> [Proposal] Refactor unwrap

Playground/RxSwiftExtPlayground.playground/Pages/Index.xcplaygroundpage/Contents.swift, Playground/RxSwiftExtPlayground.playground/Pages/nwise.xcplaygroundpage/Contents.swift, Playground/RxSwiftExtPlayground.playground/contents.xcplayground, RxSwiftExt.xcodeproj/project.pbxproj, Source/RxSwift/nwise.swift, Tests/RxSwift/nwiseTests.swift
This PR resolves #42 using scan/filter/map.
I tried to follow the guidelines and include tests and a playground page.
=> nwise and pairwise operators

RxSwiftExt.xcodeproj/project.pbxproj, Source/RxSwift/mapAt.swift, Source/RxSwift/zipWith.swift, Tests/RxSwift/MapAtTests.swift, Tests/RxSwift/ZipWithTest.swift
No big deal here. I just added a swiftlint run script phase in order to have swiftlint warning directly in Xcode in order to don't have to wait circleci output to see if there are errors.
Then I fixed all warnings for a clean codebase ✨
=> Fix Swiftlint warnings & Add build phase

CHANGELOG.md, Playground/RxSwiftExtPlayground.playground/Pages/Index.xcplaygroundpage/Contents.swift, Playground/RxSwiftExtPlayground.playground/Pages/ofType.xcplaygroundpage/Contents.swift, Playground/RxSwiftExtPlayground.playground/contents.xcplayground, Readme.md, RxSwiftExt.xcodeproj/project.pbxproj, Source/RxSwift/ofType.swift, Tests/RxSwift/Observable+OfTypeTests.swift
- Implement `ofType` operator using `filter` and `map` operator.
- Add `ofType` extension methods on `ObservableType`
=> OfType Operator

Readme.md, RxSwiftExt.podspec
=> Make pod install RxSwift/RxCocoa extensions by defaults

CHANGELOG.md, Playground/RxSwiftExtPlayground.playground/Pages/Index.xcplaygroundpage/Contents.swift, Playground/RxSwiftExtPlayground.playground/Pages/count.xcplaygroundpage/Contents.swift, Playground/RxSwiftExtPlayground.playground/contents.xcplayground, Readme.md, RxSwiftExt.xcodeproj/project.pbxproj, Source/RxSwift/count.swift, Tests/RxSwift/CountTests.swift
#43 
Add count operator, tests and playground demo.
=> Add count operator

Source/RxCocoa/partition+RxCocoa.swift, Source/RxSwift/partition.swift
Optimization discussed in #193.
=> Partition - do a single pass for predicate

CHANGELOG.md, Playground/RxSwiftExtPlayground.playground/Pages/Index.xcplaygroundpage/Contents.swift, Playground/RxSwiftExtPlayground.playground/Pages/mergeWith.xcplaygroundpage/Contents.swift, Playground/RxSwiftExtPlayground.playground/Pages/zipWith.xcplaygroundpage/Contents.swift, Playground/RxSwiftExtPlayground.playground/contents.xcplayground, Readme.md, RxSwiftExt.xcodeproj/project.pbxproj, Source/RxSwift/mergeWith.swift, Tests/RxSwift/MergeWithTests.swift
In this PR I created an operator that merges `self` with another `observable`. 
(**soon**: playground and test)
=> merge(with:) operator 

.circleci/config.yml, .gitignore, CHANGELOG.md, Package.swift, RxSwiftExt.xcodeproj/project.pbxproj, RxSwiftExt.xcworkspace/contents.xcworkspacedata, Source/RxCocoa/UIScrollView+reachedBottom.swift, Tests/RxCocoa/UIScrollView+reachedBottomTests.swift, Tests/RxCocoa/UIViewPropertyAnimatorTests+Rx.swift
https://github.com/RxSwiftCommunity/RxSwiftExt/issues/228
=> Add Swift Package Manager support

Readme.md, Source/RxSwift/filterMap.swift
https://github.com/RxSwiftCommunity/RxSwiftExt/issues/224
=> Fix filterMap doc #trivial

Source/RxSwift/pausableBuffered.swift, Tests/RxSwift/pausableBufferedTests.swift
pausableBuffered currently suffers from some issues with reentrancy.
1. If you trigger a flush while one is already happening, you'll end up with a duplicate flush happening in the middle of the first one. Among other ways, this can happen if the pauser is reentrant.
2. If you send in another value while a flush is happening, it will be emitted immediately, disrupting the original order of events. Among other ways, this can happen if the underlying observable is reentrant.
This pull request fixes this by:
1. Instead of each flush restarting from the beginning, the flushes share and increment a collective flush index.
2. The pauser is filtered through distinctUntilChanged, and the pause status is only updated _after_ the any triggered flush is completed. This way, events that come in …
=> Make pausableBuffered robust to reentrancy

Playground/RxSwiftExtPlayground.playground/Pages/mergeWith.xcplaygroundpage/Contents.swift, RxSwiftExt.xcodeproj/project.pbxproj, Source/RxSwift/mergeWith.swift
=> merge(with:) array version

.circleci/config.yml, CHANGELOG.md, RxSwiftExt.xcodeproj/project.pbxproj, RxSwiftExt.xcodeproj/xcshareddata/xcschemes/RxSwiftExt-iOS.xcscheme, RxSwiftExt.xcodeproj/xcshareddata/xcschemes/RxSwiftExt-macOS.xcscheme, RxSwiftExt.xcodeproj/xcshareddata/xcschemes/RxSwiftExt-tvOS.xcscheme, RxSwiftExt.xcodeproj/xcshareddata/xcschemes/RxSwiftExtPlayground.xcscheme, RxSwiftExt.xcodeproj/xcshareddata/xcschemes/RxSwiftExtTests-iOS.xcscheme, RxSwiftExt.xcodeproj/xcshareddata/xcschemes/RxSwiftExtTests-macOS.xcscheme, RxSwiftExt.xcodeproj/xcshareddata/xcschemes/RxSwiftExtTests-tvOS.xcscheme, Source/RxSwift/retryWithBehavior.swift, Tests/RxSwift/MergeWithTests.swift, Tests/RxSwift/andTests.swift, scripts/bootstrap-if-needed.sh, scripts/bootstrap.sh
- Updates RepeatBehavior documentation to be in correspondence with RxSwift retry operator and the current logic
=> RepeatBehavior documentation update

RxSwiftExt.xcodeproj/project.pbxproj, Source/Tools/Observable+Alias.swift
Observable-Alias.swift was missing targets and references in the project file. Added in this PR
#trivial
=> Added Observable+Alias.swift to project file with correct targets. #trivial
