RxSwiftCommunity/RxSwiftExt

- Demo/RxSwiftExtDemo/RxSwiftExtPlayground.playground/Pages/retryWithBehavior.xcplaygroundpage/Contents.swift
RxTest isn't included in the main target, so playground page doesn't compile. this PR removes the import
> removes import to RxTests in the playground page

- Demo/RxSwiftExtDemo.xcodeproj/project.pbxproj
- Demo/RxSwiftExtDemo/RxSwiftExtPlayground.playground/Pages/Index.xcplaygroundpage/Contents.swift
- Demo/RxSwiftExtDemo/RxSwiftExtPlayground.playground/Pages/repeatWithBehavior.xcplaygroundpage/Contents.swift
- Demo/RxSwiftExtDemo/RxSwiftExtPlayground.playground/Pages/retryWithBehavior.xcplaygroundpage/Contents.swift
- Demo/RxSwiftExtDemo/RxSwiftExtPlayground.playground/contents.xcplayground
- Demo/RxSwiftExtDemoTests/RetryWithBehaviorTests.swift
- Demo/RxSwiftExtDemoTests/repeatWithBehaviorTests.swift
- Source/repeatWithBehavior.swift
- Source/retryWithBehavior.swift
@fpillet - coded this one in the way you suggested - pr includes playground page + tests (mostly copied from the retry op)
since `repeat` is a reserved word in swift I implemented it as `repeatWithBehavior`, what do you think about that? Not coherent with the `retry` operator but it doesn't require backticks to use ...
> Repeat on complete

- Source/unwrap.swift
The comment for `isEmpty()` does not match the way it operates.
> Fix erroneous comment.

- .gitignore
- .travis.yml
- RxSwiftExt.xcodeproj/project.pbxproj
Hello.
I made some changes in project in order to fix Travis-CI builds. Main thing that I did: I changed SWIFT_VERSION from 3.0.1 to 3.0, because Travis builds project with XCode 8.0 and it seems XCode doesn't understand newer Swift version:)
I also changed Travis config, now it uses xcodebuild to directly build two Rx schemes (RxSwift and RxTests), this fix significantly reduces Travis build time.
> Fix Travis build

- CONTRIBUTING.md
- Playground/RxSwiftExtPlayground.playground/Pages/materialize.xcplaygroundpage/Contents.swift
- Playground/RxSwiftExtPlayground.playground/contents.xcplayground
- Readme.md
- RxSwiftExt.xcodeproj/project.pbxproj
- Source/materialize.swift
- Tests/materializeTests.swift
Includes the operators, tests, playground page, and Readme doc.
I noticed that the instructions for Carthage don't have --no-use-binaries, so I added that to the Contributing doc. But I didn't make the change to the playground files. Might want to consider that as well.
> Add materialize/dematerialize operators

- RxSwiftExt.podspec
Loosen RxSwift minimum version dependency to support RxSwift 3.1.0 along side 3.0.x
Solves https://github.com/RxSwiftCommunity/RxSwiftExt/issues/66
> Loosen RxSwift minimum version dependency

- RxSwiftExt.xcodeproj/project.pbxproj
This PR adds the APPLICATION_EXTENSION_API_ONLY flag to all targets. This is necessary if RxSwiftExt should be used in an app extension, like the top shelf on tvOS. It will basically just warn if any APIs that aren't supported in extensions are used.
The other thing that I added (and I can remove quickly if unwanted) is that the sources folder was pointing to an invalid location on disk called NSObject_Rx.
> Added app extension support

- CHANGELOG.md
- Playground/RxSwiftExtPlayground.playground/Pages/Index.xcplaygroundpage/Contents.swift
- Playground/RxSwiftExtPlayground.playground/Pages/mapTo.xcplaygroundpage/Contents.swift
- Playground/RxSwiftExtPlayground.playground/contents.xcplayground
- Source/RxSwift/mapTo.swift
- Tests/RxSwift/mapToTests.swift
This is to avoid conflicts with RxSwift's `map` operator, where the
Swift compiler would use RxSwiftExt's  `map(to:)` when `map` is being used
in its trailing closure form.
To eliminate any ambiguity, we chose to stay away from hidden compiler misdirections.
Fixes #117
> Rolled back `map(to:)` to `mapTo(_)`

- .gitignore
- CHANGELOG.md
- Playground/RxSwiftExtPlayground.playground/Pages/zipWith.xcplaygroundpage/Contents.swift
- Readme.md
- RxSwiftExt.xcodeproj/project.pbxproj
- RxSwiftExt.xcodeproj/xcshareddata/xcschemes/RxSwiftExtTests-iOS.xcscheme
- RxSwiftExt.xcodeproj/xcshareddata/xcschemes/RxSwiftExtTests-macOS.xcscheme
- Source/RxSwift/zipWith.swift
- Tests/RxSwift/ZipWithTest.swift
This PR adds a convenience operator to `ObservableConvertibleType.zip(with:)` that zips two observable sequences into one sequence on the same Rx Monad.
I thought this operator could be pretty convenient even though zip being a symmetric operator.
Since I've seen and used it quite often in Android/Java projects where the [zipWith](http://reactivex.io/documentation/operators/zip.html#collapseRxJava%C2%A02%E2%80%A4x) operator is available.
I intended it to be a shortcut for:
```
Observable.just(something)
.flatMap { Observable.zip(Observable.just($0), Observable.create { ... }) { join($0, $1) }
```
to:
```
Observable.just(something)
.zip(with: Observable.create { ... }) { join($0, $1) }
```
IRL this becomes useful when you have more operators than only Observable.just() on an observable …
> zip(with:) extension

- RxSwiftExt.xcodeproj/project.pbxproj
#trivial 
CI Had an issue so we didn't catch the fact that #136 didn't add the new operator for tvOS and macOS targets.
> Fix mapAt for macOS & tvOS

- Cartfile
Just a small adjustment to the RxSwift required version. It should now use the latest version of RxSwift.
> Soften RxSwift dependency for Carthage

- CHANGELOG.md
- Playground/RxSwiftExtPlayground.playground/Pages/Index.xcplaygroundpage/Contents.swift
- Playground/RxSwiftExtPlayground.playground/Pages/withUnretained.xcplaygroundpage/Contents.swift
- Playground/RxSwiftExtPlayground.playground/contents.xcplayground
- Readme.md
- RxSwiftExt.xcodeproj/project.pbxproj
- Source/RxSwift/withUnretained.swift
- Tests/RxSwift/WithUnretainedTests.swift
The `withUnowned(_:)` operator provides an unowned, safe to use (i.e. not implicitly unwrapped), reference to an object along with the values of the sequence.
```swift
class Displayer {
init() { }
deinit {
print("deinit")
}
func display(_ value: Any) {
print(value)
}
}
let publishSubject = PublishSubject<Int>()
var displayer: Displayer? = Displayer()
if let displayer = displayer {
_ = publishSubject
.withUnowned(displayer) // -> Observable<(Displayer, Int)>
.subscribe(onNext: { displayer, i in
displayer.display(i)
})
}
publishSubject.onNext(1)
publishSubject.onNext(2)
publishSubject.onNext(3)
publishSubject.onNext(5)
publishSubject.onNext(8)
displayer = nil // the object referenced by `displayer` gets deallocated
publishSubject.onNext(13)
publishSubject.onNext(21) …
```
> Implement withUnretained operator

- .circleci/config.yml
- CHANGELOG.md
- Cartfile.resolved
- Playground/RxSwiftExtPlayground.playground/Pages/Index.xcplaygroundpage/Contents.swift
- Playground/RxSwiftExtPlayground.playground/Pages/mapMany.xcplaygroundpage/Contents.swift
- Playground/RxSwiftExtPlayground.playground/Pages/toSortedArray.xcplaygroundpage/Contents.swift
- Playground/RxSwiftExtPlayground.playground/contents.xcplayground
- RxSwiftExt.xcodeproj/project.pbxproj
- Source/RxSwift/mapMany.swift
- Tests/RxSwift/MapManyTests.swift
- Tests/RxSwift/ToSortedArrayTests.swift
For the proposed operator #93 🎉
> mapMany Operator

- CHANGELOG.md
- Source/RxSwift/withUnretained.swift
- Tests/RxSwift/WithUnretainedTests.swift
This is based on a change in [SE-0110](https://github.com/apple/swift-evolution/blob/master/proposals/0110-distingish-single-tuple-arg.md) 
the gist is, in the existing implementation you can’t do 
```swift
.withUnretained(self)
.flatMap { owner, value in … }
```
Since a single parentheses pair is not considered an explicit tuple, so does not support splatting correctly. 
Without this change you have to do
```swift
.withUnretained(self)
.flatMap { tuple in … tuple.0, tuple.1 }
```
This retains backward compatibility with the explicit `tuple.0` implementation, so there are no breaking changes here. 
Thanks to @sgtsquiggs for noticing this.
> Make withUnretained explicitly use a selector

- CHANGELOG.md
- Source/RxCocoa/mapTo+RxCocoa.swift
- Tests/RxCocoa/MapToTests+RxCocoa.swift
The `map(to:)` function was rolled back to the name `mapTo(_:)` for `ObservableType` in https://github.com/RxSwiftCommunity/RxSwiftExt/pull/121. The change wasn't made for `SharedSequenceConvertibleType`, though.
So, now I have a project with a bunch of `map(to:)`s and `mapTo(_:)`s 🙃.
It would be nice to have convergence here!
> Roll `map(to:)` back to `mapTo(_:)` for `SharedSequenceConvertibleType`

- CHANGELOG.md
- Playground/RxSwiftExtPlayground.playground/Pages/Index.xcplaygroundpage/Contents.swift
- Playground/RxSwiftExtPlayground.playground/Pages/partition.xcplaygroundpage/Contents.swift
- Readme.md
- RxSwiftExt.xcodeproj/project.pbxproj
- Source/RxCocoa/partition+RxCocoa.swift
- Source/RxSwift/partition.swift
- Tests/RxCocoa/PartitionTests+RxCocoa.swift
- Tests/RxSwift/PartitionTests.swift
This is a new operator we've been using in our codebase that seems generic and useful, and I think would be a good fit here :) 
Partition would split a stream into two streams - one with elements matching the predicate, and one with elements not with matching the predicate.
The name partition came from Haskell: http://hackage.haskell.org/package/base-4.12.0.0/docs/Data-List.html#v:partition
This lets you do things like 
```swift
let numbers = Observable.of(1, 2, 3, 4, 5, 6)
let (evens, odds) = numbers.partition { $0 % 2 == 0 }
_ = evens.debug("even").subscribe() // emits 2, 4, 6
_ = odds.debug("odds").subscribe() // emits 1, 3, 5
// Another example:
let currentState: Observable<State> = ...
let (isLoading, isIdle) = currentState.partition { $0 == .loading }
```
Would appreciate your …
> Partition operator

- CHANGELOG.md
- Source/RxSwift/fromAsync.swift
- Tests/RxSwift/fromAsyncTests.swift
I think the current implementation of `fromAsync` might be a little more useful. Completion handlers used to be `(result: T, error: CustomError)` closures. Also completion handler should emit only once. So i used `Single` to implement that
> [feature/fromAsync] add from async for single

- CHANGELOG.md
- Source/RxSwift/once.swift
Resolve https://github.com/RxSwiftCommunity/RxSwiftExt/issues/200
@freak4pc mentioned that adding RxAtomic as dependency is an unwanted solution, so here is yet another `AtomicInt` implementation with few needed operators. Tests were just copied from `RxSwift` repo
> `once`: Use NSRecursiveLock instead of deprecated OSAtomicOr32OrigBarrier

- CHANGELOG.md
- Source/RxSwift/mapTo.swift
- Tests/RxSwift/mapToTests.swift
There was a discussion in RxSwift slack, that few handy operators are implemented only for `Observable`. This PR adds `.mapTo` for Single and Maybe.
I have a few prod examples when I don't interested in `Single` actual result, however, I can't use `Completable`.
```swift
let single: Single<Model> = service.get().share()
single.subscribe(onSuccess: { *interested in success value* })
single.mapTo(true).bind(to: subject) // not interested in success value
```
> Added `mapTo` for `Single` and `Maybe`

- CHANGELOG.md
- Source/RxSwift/apply.swift
- Tests/RxSwift/applyTests.swift
Same motivation with `Single.apply`. I have network layer and basic policy (retry, network activity indicator, logging etc.) which I want to apply to all my requests (which can be `Single`, `Maybe` and `Completable`)
> Add `apply` for Single, Maybe & Completable

- Source/RxSwift/unwrap.swift
Based on https://github.com/RxSwiftCommunity/RxSwiftExt/pull/229 sadly can't push changes there
> Change unwrap impl to use compactMap

- Tests/RxSwift/MergeWithTests.swift
- Tests/RxSwift/Observable+OfTypeTests.swift
- Tests/RxSwift/WeakTarget.swift
- Tests/RxSwift/WeakTests.swift
- Tests/RxSwift/ZipWithTest.swift
- Tests/RxSwift/andTests.swift
- Tests/RxSwift/fromAsyncTests.swift
- Tests/RxSwift/nwiseTests.swift
- Tests/RxSwift/repeatWithBehaviorTests.swift
- Tests/RxSwift/retryWithBehaviorTests.swift
RxSwift main repo use this strategy to avoid countless `private struct MyError: Swift.Error`. We actually need only one test error type for whole project, no need to create own on every class.
In case of complicated error logic (which i can't see now) custom private type can be created
> Remove dublicated test errors #trivial

- Source/RxCocoa/mapTo+RxCocoa.swift
- Source/RxCocoa/unwrap+SharedSequence.swift
- Source/RxSwift/ObservableType+Weak.swift
- Source/RxSwift/and.swift
- Source/RxSwift/bufferWithTrigger.swift
- Source/RxSwift/cascade.swift
- Source/RxSwift/ofType.swift
- Source/RxSwift/pausable.swift
- Source/RxSwift/pausableBuffered.swift
- Source/RxSwift/unwrap.swift
- Source/RxSwift/withUnretained.swift
- Source/RxSwift/zipWith.swift
It's better for readability to avoid one character generics naming. RxSwift already replaced all generics to meaningful title, it's RxSwiftExt turn
P.S. lol, i found that project uses tabs as indents. I am not sure, should i indent new code with tabs or spaces
> Reduce one character generics usage #trivial

- RxSwiftExt.xcodeproj/project.pbxproj
Hello RxSwiftExt maintainers!
The main app I work on uses RxSwiftExt and does not use any package managers to integrate it. RxSwiftExt is integrated in a codebase containing both macOS and iOS code. We ran into an issue where our Mac target would no longer compiled saying RxCocoa was missing when compiling RxSwiftExt. This issue was non-existant when using RxSwiftExt with our iOS target.
While looking at the Package.swift & the RxSwiftExt.podspec files, the dependency to RxSwift is set correctly. When you integrate the Xcode Project to compile RxSwiftExt yourself, only the iOS target was linking correctly to its dependencies.
Moreover, I removed linking to RxRelay since no target was using it.
> Link to RxCocoa on macOS & tvOS targets

- Source/RxSwift/fromAsync.swift
Changes the documentation to make more grammatical sense + spelling fix.
> `fromAsync` - Minior doc fix [#trivial ]

- Cartfile
- RxSwiftExt.xcodeproj/project.pbxproj
I'd like to use this library with Carthage, However, some settings are broken, so we can't build this with Carthage.
There are two problems.
- We can't use this library with Carthage regularly
- We can't use this library with Carthage in XCFramework
Xcode 12.4
```
github "RxSwiftCommunity/RxSwiftExt" "7cae93b7795fb7b4ecf617aec5f1c0f1fc8fb0e6" # current main HEAD
```
```console
$ carthage bootstrap --platform ios --use-xcframeworks --cache-builds
*** Building scheme "RxSwiftExt-iOS" in RxSwiftExt.xcworkspace
Build Failed
Task failed with exit code 65:
/usr/bin/xcrun xcodebuild -workspace /Users/giginet/work/CarthagePlayground/Carthage/Checkouts/RxSwiftExt/RxSwiftExt.xcworkspace -scheme RxSwiftExt-iOS -configuration Release -derivedDataPath …
```
> Fix Carthage integration

- .gitmodules
There is a reference to Rx.xcodeproj in the project, and without this it does not build if you don't use Carthage.
It's essentially the same fix as https://github.com/RxSwiftCommunity/RxDataSources/commit/98ae6d937f37766187f97cd066076fa7127cff01
> Added RxSwift submodule dependency
